name: Linting test for datashare-extension-nlp-spacy

on:
  push:
    branches: [ 'main' ]
  pull_request:
    paths:
      - 'datashare_spacy_worker/**.py'
      - '.github/workflows/*-worker.yml'

# TODO: leverage some caching here
jobs:
  linting-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pylint
        with:
          path: "."

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
