name: Linting tests for datashare-extension-nlp-spacy

on:
  push:
    branches: [ 'main' ]
  pull_request:
    paths:
      - 'src/**.*'
      - '.github/workflows/*-extension.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn validate
        mvn checkstyle:check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
