name: Test for spacy worker

on:
  push:
    branches: [ 'main' ]
  pull_request:
    paths:
      - 'datashare_spacy_worker/**.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/*-worker.yml'

jobs:
  test-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: format --check --config qa/ruff.toml
          version: 0.11.2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.6.7"
          python-version: "3.10"
          enable-cache: true
      - name: Setup Python project
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Run tests
        run: uv run --dev --frozen pytest -vvv --cache-clear --show-capture=all -r A tests
    services:
      elasticsearch:
        image: elasticsearch:7.17.25
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200"
          --health-interval 3s
          --health-timeout 1s
          --health-retries 10
          --health-start-period 5s
        ports:
          - "9200:9200"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
