name: Test for spacy worker

on:
  push:
    branches: [ 'main' ]
  pull_request:
    paths:
      - 'datashare_spacy_worker/**.py'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/*-worker.yml'

jobs:
  test-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          jupyter: true
          src: "."
          version: "~= 24.2.0"
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python project
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry
      - run: poetry install -v --with dev --all-extras --sync
      # Poetry doesn't support symlinks to outside of the project so we have to force copy the models.json
      - name: Run tests
        run: |
          cp --remove-destination data/models.json datashare_spacy_worker/data
          poetry run python -m spacy download en_core_web_trf
          poetry run python -m pytest -vvv --cache-clear --show-capture=all -r A .

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
