name: Test for spacy worker

on:
  push:
    branches: [ 'main' ]
  pull_request:
    paths:
      - 'datashare_spacy_worker/**.py'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/*-worker.yml'

jobs:
  test-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          jupyter: true
          src: "."
          version: "~= 24.2.0"
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python project
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry
      - run: poetry install -v --with dev --sync
      # Poetry doesn't support symlinks to outside of the project so we have to force copy the models.json
      - name: Run tests
        run: |
          cp --remove-destination data/models.json datashare_spacy_worker/data
          poetry run python -m pytest -vvv --cache-clear --show-capture=all -r A .
    services:
      elasticsearch:
        image: elasticsearch:7.17.25
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200"
          --health-interval 3s
          --health-timeout 1s
          --health-retries 10
          --health-start-period 5s
        ports:
          - "9200:9200"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
