name: Test for spacy worker

on:
  push:
    branches: [ 'main' ]
  pull_request:
    paths:
      - 'datashare-spacy-worker/**.py'
      - '.github/workflows/*-worker.yml'

jobs:
  test-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          jupyter: true
          src: "datashare-spacy-worker"
          version: "~= 24.2.0"
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python project
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry
      - run: cd datashare-spacy-worker && poetry install -v --with dev --sync
      - name: Run tests
        run: |
          cd datashare-spacy-worker
          poetry run python -m pytest -vvv --cache-clear --show-capture=all -r A .

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
